name = my_misc_doors
description = Some misc. doors.
depends = default, my_door_wood, doors, wool
optional_depends = screwdriver
author = Don Michaud
title = My Miscellaneous Doors
min_minetest_version = 0.4.10
